name: Reusable CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    permissions: write-all
    uses: testthatsk/.github/.github/workflows/ci-java-testing.yml@main

